 cout<<"0) nero; "         <<endl;
 cout<<"1) blu; "          <<endl;
 cout<<"2) verde; "        <<endl;
 cout<<"3) verde acqua; "  <<endl;
 cout<<"4) bordeaux; "     <<endl;
 cout<<"5) viola; "        <<endl;
 cout<<"6) verde oliva; "  <<endl;
 cout<<"7) grigio chiaro; "<<endl; 
 cout<<"8) grigio; "       <<endl;
 cout<<"9) blu; "          <<endl;
 cout<<""<<endl;
